version: '3'

tasks:
  clean:
    cmds:
      - rm -rf ./out
  deps:
    cmds:
      - go get github.com/bendahl/uinput
      - go get github.com/go-gl/gl/v2.1/gl
      - go get github.com/go-gl/glfw/v3.3/glfw
      - go get github.com/go-gl/gltext
  build:
    cmds:
      - task: clean
      - task: deps
      - go build -o out/ratazana -v ./...
  run:
    cmds:
      - go run -v ./...
